name: Continuous

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest 
    env:
      CONFIGURATION: Release
    steps:
    - name: Checkout FriendlyWordsDotNet
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Get words files
      run: tools/get-words.sh
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --no-restore -c ${{ env.CONFIGURATION }}
      working-directory: src
    - name: Test
      uses: zyborg/dotnet-tests-report@v1
      with:
        project_path: src
        report_name: friendlywordsdotnet_tests_${{ github.run_number }}
        report_title: FriendlyWordsDotNet Tests - ${{ github.run_number }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        no_restore: true
        set_check_status_from_test_outcome: true
        msbuild_configuration: ${{ env.CONFIGURATION }}